.class public Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;
.super Ljava/lang/Object;
.source "XmlResourceUtils.java"


# static fields
.field private static final ARCH_ATTRIBUTE:Ljava/lang/String; = "com.google.firebase.crashlytics.build_ids_arch"

.field static final ARRAY_RESOURCE_FORMAT:Ljava/lang/String; = "<string-array name=\"%s\" tools:ignore=\"UnusedResources,TypographyDashes\" translatable=\"false\">\n%s</string-array>\n"

.field private static final BUILD_ID_ATTRIBUTE:Ljava/lang/String; = "com.google.firebase.crashlytics.build_ids_build_id"

.field static final ITEM_RESOURCE_FORMAT:Ljava/lang/String; = "<item>%s</item>\n"

.field private static final LIB_ATTRIBUTE:Ljava/lang/String; = "com.google.firebase.crashlytics.build_ids_lib"

.field private static final XML_ARRAY_TAG:Ljava/lang/String; = "string-array"

.field private static final XML_ITEM_TAG:Ljava/lang/String; = "item"

.field private static final XML_NAME_ATTRIBUTE:Ljava/lang/String; = "name"


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 14
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static createResourceFileStream(Ljava/util/List;)Ljava/io/InputStream;
    .locals 4
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;",
            ">;)",
            "Ljava/io/InputStream;"
        }
    .end annotation

    .line 126
    .local p0, "buildIdInfoList":Ljava/util/List;, "Ljava/util/List<Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;>;"
    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    const-string v1, "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources xmlns:tools=\"http://schemas.android.com/tools\">\n<!--\n  This file is automatically generated by Crashlytics to uniquely\n  identify the build ids for your Android application.\n\n  Do NOT modify or commit to source control!\n-->\n"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    .line 134
    invoke-static {p0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->formatLibItems(Ljava/util/List;)Ljava/lang/String;

    move-result-object v1

    const-string v2, "com.google.firebase.crashlytics.build_ids_lib"

    filled-new-array {v2, v1}, [Ljava/lang/Object;

    move-result-object v1

    const-string v2, "<string-array name=\"%s\" tools:ignore=\"UnusedResources,TypographyDashes\" translatable=\"false\">\n%s</string-array>\n"

    invoke-static {v2, v1}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    .line 135
    invoke-static {p0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->formatArchItems(Ljava/util/List;)Ljava/lang/String;

    move-result-object v1

    const-string v3, "com.google.firebase.crashlytics.build_ids_arch"

    filled-new-array {v3, v1}, [Ljava/lang/Object;

    move-result-object v1

    invoke-static {v2, v1}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    .line 136
    invoke-static {p0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->formatBuildIdItems(Ljava/util/List;)Ljava/lang/String;

    move-result-object v1

    const-string v3, "com.google.firebase.crashlytics.build_ids_build_id"

    filled-new-array {v3, v1}, [Ljava/lang/Object;

    move-result-object v1

    invoke-static {v2, v1}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    const-string v1, "</resources>\n"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 139
    .local v0, "xml":Ljava/lang/String;
    new-instance v1, Ljava/io/ByteArrayInputStream;

    invoke-virtual {v0}, Ljava/lang/String;->getBytes()[B

    move-result-object v2

    invoke-direct {v1, v2}, Ljava/io/ByteArrayInputStream;-><init>([B)V

    return-object v1
.end method

.method private static formatArchItems(Ljava/util/List;)Ljava/lang/String;
    .locals 5
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;",
            ">;)",
            "Ljava/lang/String;"
        }
    .end annotation

    .line 104
    .local p0, "buildIdInfoList":Ljava/util/List;, "Ljava/util/List<Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;>;"
    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    .line 105
    .local v0, "items":Ljava/lang/StringBuilder;
    invoke-interface {p0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v1

    :goto_0
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v2

    if-eqz v2, :cond_0

    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;

    .line 106
    .local v2, "buildIdInfo":Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;
    nop

    .line 107
    invoke-virtual {v2}, Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;->getArch()Ljava/lang/String;

    move-result-object v3

    filled-new-array {v3}, [Ljava/lang/Object;

    move-result-object v3

    .line 106
    const-string v4, "<item>%s</item>\n"

    invoke-static {v4, v3}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 108
    .end local v2    # "buildIdInfo":Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;
    goto :goto_0

    .line 109
    :cond_0
    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    return-object v1
.end method

.method private static formatBuildIdItems(Ljava/util/List;)Ljava/lang/String;
    .locals 5
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;",
            ">;)",
            "Ljava/lang/String;"
        }
    .end annotation

    .line 113
    .local p0, "buildIdInfoList":Ljava/util/List;, "Ljava/util/List<Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;>;"
    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    .line 114
    .local v0, "items":Ljava/lang/StringBuilder;
    invoke-interface {p0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v1

    :goto_0
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v2

    if-eqz v2, :cond_0

    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;

    .line 115
    .local v2, "buildIdInfo":Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;
    nop

    .line 116
    invoke-virtual {v2}, Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;->getBuildId()Ljava/lang/String;

    move-result-object v3

    filled-new-array {v3}, [Ljava/lang/Object;

    move-result-object v3

    .line 115
    const-string v4, "<item>%s</item>\n"

    invoke-static {v4, v3}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 117
    .end local v2    # "buildIdInfo":Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;
    goto :goto_0

    .line 118
    :cond_0
    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    return-object v1
.end method

.method private static formatLibItems(Ljava/util/List;)Ljava/lang/String;
    .locals 5
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List<",
            "Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;",
            ">;)",
            "Ljava/lang/String;"
        }
    .end annotation

    .line 95
    .local p0, "buildIdInfoList":Ljava/util/List;, "Ljava/util/List<Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;>;"
    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    .line 96
    .local v0, "items":Ljava/lang/StringBuilder;
    invoke-interface {p0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v1

    :goto_0
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v2

    if-eqz v2, :cond_0

    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;

    .line 97
    .local v2, "buildIdInfo":Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;
    nop

    .line 98
    invoke-virtual {v2}, Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;->getLibraryName()Ljava/lang/String;

    move-result-object v3

    filled-new-array {v3}, [Ljava/lang/Object;

    move-result-object v3

    .line 97
    const-string v4, "<item>%s</item>\n"

    invoke-static {v4, v3}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 99
    .end local v2    # "buildIdInfo":Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;
    goto :goto_0

    .line 100
    :cond_0
    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v1

    return-object v1
.end method

.method private static getArchElement(Lorg/w3c/dom/Document;)Lorg/w3c/dom/Element;
    .locals 1
    .param p0, "doc"    # Lorg/w3c/dom/Document;

    .line 72
    const-string v0, "com.google.firebase.crashlytics.build_ids_arch"

    invoke-static {p0, v0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->getResourceElement(Lorg/w3c/dom/Document;Ljava/lang/String;)Lorg/w3c/dom/Element;

    move-result-object v0

    return-object v0
.end method

.method public static getBuildIds(Lorg/w3c/dom/Document;)Ljava/util/List;
    .locals 9
    .param p0, "doc"    # Lorg/w3c/dom/Document;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lorg/w3c/dom/Document;",
            ")",
            "Ljava/util/List<",
            "Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;",
            ">;"
        }
    .end annotation

    .line 53
    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    .line 55
    .local v0, "buildIdInfoList":Ljava/util/List;, "Ljava/util/List<Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;>;"
    invoke-static {p0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->getLibElement(Lorg/w3c/dom/Document;)Lorg/w3c/dom/Element;

    move-result-object v1

    const-string v2, "item"

    invoke-interface {v1, v2}, Lorg/w3c/dom/Element;->getElementsByTagName(Ljava/lang/String;)Lorg/w3c/dom/NodeList;

    move-result-object v1

    .line 56
    .local v1, "libs":Lorg/w3c/dom/NodeList;
    invoke-static {p0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->getArchElement(Lorg/w3c/dom/Document;)Lorg/w3c/dom/Element;

    move-result-object v3

    invoke-interface {v3, v2}, Lorg/w3c/dom/Element;->getElementsByTagName(Ljava/lang/String;)Lorg/w3c/dom/NodeList;

    move-result-object v3

    .line 57
    .local v3, "archs":Lorg/w3c/dom/NodeList;
    invoke-static {p0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->getBuildIdsElement(Lorg/w3c/dom/Document;)Lorg/w3c/dom/Element;

    move-result-object v4

    invoke-interface {v4, v2}, Lorg/w3c/dom/Element;->getElementsByTagName(Ljava/lang/String;)Lorg/w3c/dom/NodeList;

    move-result-object v2

    .line 58
    .local v2, "buildIds":Lorg/w3c/dom/NodeList;
    const/4 v4, 0x0

    .local v4, "i":I
    :goto_0
    invoke-interface {v2}, Lorg/w3c/dom/NodeList;->getLength()I

    move-result v5

    if-ge v4, v5, :cond_0

    .line 59
    invoke-interface {v1, v4}, Lorg/w3c/dom/NodeList;->item(I)Lorg/w3c/dom/Node;

    move-result-object v5

    invoke-interface {v5}, Lorg/w3c/dom/Node;->getTextContent()Ljava/lang/String;

    move-result-object v5

    .line 60
    .local v5, "lib":Ljava/lang/String;
    invoke-interface {v3, v4}, Lorg/w3c/dom/NodeList;->item(I)Lorg/w3c/dom/Node;

    move-result-object v6

    invoke-interface {v6}, Lorg/w3c/dom/Node;->getTextContent()Ljava/lang/String;

    move-result-object v6

    .line 61
    .local v6, "arch":Ljava/lang/String;
    invoke-interface {v2, v4}, Lorg/w3c/dom/NodeList;->item(I)Lorg/w3c/dom/Node;

    move-result-object v7

    invoke-interface {v7}, Lorg/w3c/dom/Node;->getTextContent()Ljava/lang/String;

    move-result-object v7

    .line 62
    .local v7, "buildId":Ljava/lang/String;
    new-instance v8, Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;

    invoke-direct {v8, v5, v6, v7}, Lcom/google/firebase/crashlytics/buildtools/buildids/BuildIdInfo;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    invoke-interface {v0, v8}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 58
    .end local v5    # "lib":Ljava/lang/String;
    .end local v6    # "arch":Ljava/lang/String;
    .end local v7    # "buildId":Ljava/lang/String;
    add-int/lit8 v4, v4, 0x1

    goto :goto_0

    .line 64
    .end local v4    # "i":I
    :cond_0
    return-object v0
.end method

.method private static getBuildIdsElement(Lorg/w3c/dom/Document;)Lorg/w3c/dom/Element;
    .locals 1
    .param p0, "doc"    # Lorg/w3c/dom/Document;

    .line 76
    const-string v0, "com.google.firebase.crashlytics.build_ids_build_id"

    invoke-static {p0, v0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->getResourceElement(Lorg/w3c/dom/Document;Ljava/lang/String;)Lorg/w3c/dom/Element;

    move-result-object v0

    return-object v0
.end method

.method private static getLibElement(Lorg/w3c/dom/Document;)Lorg/w3c/dom/Element;
    .locals 1
    .param p0, "doc"    # Lorg/w3c/dom/Document;

    .line 68
    const-string v0, "com.google.firebase.crashlytics.build_ids_lib"

    invoke-static {p0, v0}, Lcom/google/firebase/crashlytics/buildtools/buildids/XmlResourceUtils;->getResourceElement(Lorg/w3c/dom/Document;Ljava/lang/String;)Lorg/w3c/dom/Element;

    move-result-object v0

    return-object v0
.end method

.method public static getResourceElement(Lorg/w3c/dom/Document;Ljava/lang/String;)Lorg/w3c/dom/Element;
    .locals 6
    .param p0, "doc"    # Lorg/w3c/dom/Document;
    .param p1, "elementName"    # Ljava/lang/String;

    .line 80
    const-string v0, "string-array"

    invoke-interface {p0, v0}, Lorg/w3c/dom/Document;->getElementsByTagName(Ljava/lang/String;)Lorg/w3c/dom/NodeList;

    move-result-object v0

    .line 81
    .local v0, "strings":Lorg/w3c/dom/NodeList;
    const/4 v1, 0x0

    .line 82
    .local v1, "element":Lorg/w3c/dom/Element;
    const/4 v2, 0x0

    .local v2, "i":I
    :goto_0
    invoke-interface {v0}, Lorg/w3c/dom/NodeList;->getLength()I

    move-result v3

    if-ge v2, v3, :cond_1

    .line 83
    invoke-interface {v0, v2}, Lorg/w3c/dom/NodeList;->item(I)Lorg/w3c/dom/Node;

    move-result-object v3

    check-cast v3, Lorg/w3c/dom/Element;

    .line 84
    .local v3, "el":Lorg/w3c/dom/Element;
    const-string v4, "name"

    invoke-interface {v3, v4}, Lorg/w3c/dom/Element;->hasAttribute(Ljava/lang/String;)Z

    move-result v5

    if-eqz v5, :cond_0

    .line 85
    invoke-interface {v3, v4}, Lorg/w3c/dom/Element;->getAttribute(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v4

    invoke-virtual {v4, p1}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z

    move-result v4

    if-eqz v4, :cond_0

    .line 86
    move-object v1, v3

    .line 87
    goto :goto_1

    .line 82
    .end local v3    # "el":Lorg/w3c/dom/Element;
    :cond_0
    add-int/lit8 v2, v2, 0x1

    goto :goto_0

    .line 91
    .end local v2    # "i":I
    :cond_1
    :goto_1
    return-object v1
.end method
